# Generated by Django 5.1.6 on 2025-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ImageField(default='images/mosque1.jpg', upload_to='event_images/'),
        ),
    ]
