# Generated by Django 5.1.6 on 2025-02-17 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Financial Record'},
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='related_event',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='record_type',
            field=models.CharField(choices=[('DONATION', 'Donation'), ('SPONSOR', 'Sponsorship'), ('EXPENSE', 'Expense')], max_length=10),
        ),
    ]
