# Generated by Django 5.1.6 on 2025-02-17 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reference', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('asked_on', models.DateTimeField(auto_now_add=True)),
                ('answered_on', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-asked_on'],
            },
        ),
        migrations.DeleteModel(
            name='HadithOfTheDay',
        ),
        migrations.AlterModelOptions(
            name='scholarlecture',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='scholarlecture',
            old_name='scholar_name',
            new_name='scholar',
        ),
        migrations.AddField(
            model_name='scholarlecture',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scholarlecture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
