# Generated by Django 5.1.6 on 2025-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('QURAN', 'Quran Studies'), ('HADITH', 'Hadith'), ('FIQH', 'Islamic Jurisprudence'), ('HISTORY', 'Islamic History')], max_length=10)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources/')),
                ('thumbnail', models.ImageField(upload_to='resource_thumbs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
